### ISSUE TITLE
Failed to connect localhost:29500

### ISSUE THREAD

**Issue by HDD-Team** [Lizonghang/TPI-LLM#1]
I run docker and this command 
```
python examples/run_multiprocess.py --world_size 4 --model_type llama --model_path ./Qwen2.5-14B --prompt "how are you?" --length 20 --memory_window 4
```
I get this message:
```
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.12/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/user/tttt/examples/run_multiprocess.py", line 14, in init_process
    fn(rank, args, dist=dist)
  File "/home/user/tttt/examples/run_llama.py", line 85, in main
    comm.barrier()
  File "/home/user/tttt/src/tpi_llm/distributed/comm.py", line 221, in barrier
    self._s = connect_with_retry(self._host, self._port, self._rank)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/tttt/src/tpi_llm/distributed/utils.py", line 49, in connect_with_retry
    raise ConnectionRefusedError(f"Failed to connect to {host}:{port} after {max_retry} attempts.")
ConnectionRefusedError: Failed to connect to 127.0.0.1:29500 after 10 attempts.
Process Process-2:
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.12/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/user/tttt/examples/run_multiprocess.py", line 14, in init_process
    fn(rank, args, dist=dist)
  File "/home/user/tttt/examples/run_llama.py", line 85, in main
    comm.barrier()
  File "/home/user/tttt/src/tpi_llm/distributed/comm.py", line 221, in barrier
    self._s = connect_with_retry(self._host, self._port, self._rank)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/tttt/src/tpi_llm/distributed/utils.py", line 49, in connect_with_retry
    raise ConnectionRefusedError(f"Failed to connect to {host}:{port} after {max_retry} attempts.")
ConnectionRefusedError: Failed to connect to 127.0.0.1:29500 after 10 attempts.
```

**Comment by Lizonghang** [comment]
Hello, Qwen is not supported. Only Llama-series models are tested now, e.g., Llama 2 1.1B/3B/7B/13B/70B, Llama 3 8B/70B, Llama 3.1 8B/70B, and other models based on Llama architecture, e.g., Yi-34B-llama.

**Comment by HDD-Team** [comment]
I tried the model Yi-34b, but he gives me the same mistake.

**Comment by Lizonghang** [comment]
Please use [this repo (Yi-34B-Llama)](https://huggingface.co/chargoddard/Yi-34B-Llama), not Yi-34B, because Yi-34B does not follow a standard Llama structure according to Hugging Face requirements.

**Comment by msheldon32** [comment]
Hello, I am having a similar issue with Nandini82/Llama-2-1.1b-ft [(https://huggingface.co/Nandini82/Llama-2-1.1b-ft)](url). 

Is this a supported model?

**Comment by Lizonghang** [comment]
Hello, Nandini82/Llama-2-1.1b-ft is supported. You may need to check for other causes, e.g., did the master (with rank=0) start without any errors? Did the master successfully bind to port 29500? Can the worker access port 29500 of the master?




Li&nbsp;Zonghang
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Lizonghang/TPI-LLM"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年10月8日(星期二) 上午10:00
***@***.***&gt;;
抄送:&nbsp;"Li ***@***.******@***.***&gt;;
主题:&nbsp;Re: [Lizonghang/TPI-LLM] Failed to connect localhost:29500 (Issue #1)





 
Hello, I am having a similar issue with Nandini82/Llama-2-1.1b-ft (https://huggingface.co/Nandini82/Llama-2-1.1b-ft).
 
Is this a supported model?
